In [9]:
#1) 하나의 리스트를 만들고, 해당 리스트의 값의 결과가 첫번째:10, 두번째:20, 세번째: 30, 
#네번째 : [1,2,3] 값이 들어가도록 만드시오.
arr = [10,20,30,[1,2,3]]
print(arr)

[10, 20, 30, [1, 2, 3]]


In [13]:
#2) 해당 리스트를 인덱싱해 [1,2,3]의 값이 도출되게 하시오.
print(arr[3])

[1, 2, 3]


In [21]:
#3) 수학점수: 20, 30, 40, 50, 60, 영어점수 : 50, 70, 50, 60, 90으로 두개의 리스트로 생성하시오.
math = [20, 30, 40, 50, 60]
eng = [50, 70, 50, 60, 90]

In [17]:
# 4) https://www.youtube.com/를 www.naver.com으로 변경하시오.
url = "https://www.youtube.com/"
new = url.replace("youtube","naver")
print(new)

https://www.naver.com/


In [27]:
# 5) 해당 리스트의 값을 계산해 수학점수와 영어점수 각각의 값의 평균을 계산하시오.
print(sum(math)/len(math))
print(sum(eng)/len(eng))

40.0
64.0


In [47]:
# 6) 1,2,100,4,5, 900 해당 값을 가지는 배열을 생성하시고, 100과 900을 제거하시오.
import numpy as np
arr = np.array([1,2,100,4,5, 900])
arr = np.delete(arr, 2)
arr = np.delete(arr, arr.size-1)

# arr = arr[arr!=100]
# arr = arr[arr!=900] 

print(arr)

[1 2 4 5]


In [65]:
# 7) 문제 3번의 값을 딕셔너리 형태로 저장하시오.
d= {"math":[20, 30, 40, 50, 60], "eng":[50, 70, 50, 60, 90]}
print(d)

{'math': [20, 30, 40, 50, 60], 'eng': [50, 70, 50, 60, 90]}


In [69]:
# 8) 3번의 리스트를 딕셔너리 형태로 저장하고, 수학점수 첫번째 값과 영어점수 세번째 값의 합을 계산하시오.
d={"math":[20, 30, 40, 50, 60], "eng":[50, 70, 50, 60, 90]}
print(d["math"][0] + d["eng"][2])

70


In [146]:
# 1. 다음 리스트에서 'Python'을 출력하세요.
languages = ['C', 'Java', 'Python', 'JavaScript', 'Go']
print(languages[2])

# 2. 아래 리스트에서 마지막 요소를 출력하세요.
numbers = [10, 20, 30, 40, 50]
print(numbers[-1])

# 3. 'apple'을 'banana'로 변경한 후 리스트를 출력하세요.
fruits = ['apple', 'grape', 'cherry']
fruits[0] = 'banana'
print(fruits)


# 4. 아래 리스트에서 홀수만 출력하세요.
nums = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
print([i for i in nums if i%2==1]) #짝수만 출력
print([i*2 for i in nums]) #제곱해서 출력
print([i for i in nums if i>5]) #5이상만 출력


Python
50
['banana', 'grape', 'cherry']
[1, 3, 5, 7, 9]
[2, 4, 6, 8, 10, 12, 14, 16, 18, 20]
[6, 7, 8, 9, 10]


In [126]:
import numpy as np

# 5. 3x3 배열을 생성하고 (2,1) 위치의 요소를 출력하세요.
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(arr[2,1])

# 6. 위 배열에서 1열(두 번째 열)만 출력하세요.
# for i in range(3): #행의개수 열의 개수
#     for j in range(3):
#         if(j==1):
#             print(arr[i][j], end= ' ')
# print('\n')
print(arr[: , 1])

# 7. 1~10까지의 숫자를 가진 NumPy 배열을 만들고, 짝수만 출력하세요.
Numpy = np.array([1,2,3,4,5,6,7,8,9,10])
print(Numpy[Numpy%2==0])

print(len(arr))
print(arr.size)
print(arr.shape)

8
[2 5 8]
[ 2  4  6  8 10]
3
9
(3, 3)


In [134]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

print(arr[arr % 2 == 0])# 짝수만 선택
print(arr[arr>=5]) #5이상 값만 선택
print(arr[arr!=5]) #5아닌 값만 선택

[ 2  4  6  8 10]
[ 5  6  7  8  9 10]
[ 1  2  3  4  6  7  8  9 10]


In [166]:
# 8. 다음 딕셔너리에서 'age' 값을 출력하세요.
person = {'name': 'Alice', 'age': 25, 'city': 'Seoul'}
print(person['age'])

# 9. 'city' 값을 'Busan'으로 변경한 후 딕셔너리를 출력하세요.
person['city']='Busan'
print(person)

# 10. 아래 딕셔너리에서 모든 key를 리스트로 출력하세요.
student = {'id': 101, 'name': 'Bob', 'score': 90}
print(student.keys())
print(list(student.keys()))

print(list(a.keys()))

25
{'name': 'Alice', 'age': 25, 'city': 'Busan'}
dict_keys(['id', 'name', 'score'])
['id', 'name', 'score']
